version: '3.9'
services:
    java_db:
        container_name: pilotage_contrat
        image: postgres
        ports:
            - 5431:5432        
        environment:
            POSTGRES_USER: fms_admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: pilotage_contrat
        volumes:
            - pgdata:/data/postgres
volumes:
    pgdata: {}
